// © 2026 Benjamin Pasero. All rights reserved.
// https://github.com/bpasero/firlefanz

export interface Story {
  id: string;
  title: string;
  teaser: string;
  coverImage: string;
  prompt: string;
  pages: Page[];
  translations?: Record<string, StoryTranslation>;
  /**
   * Optional path to a looping background-music track (relative to the site root,
   * e.g. "/stories/<id>/music.mp3"). When present, the reader shows a music toggle
   * that plays this clip quietly underneath the narration. Generated by
   * scripts/generate-music.ts (OpenRouter Lyria 3 Clip). Language-agnostic.
   */
  music?: string;
}

export interface Page {
  text: string[];
  image: string;
}

export interface StoryTranslation {
  title: string;
  teaser: string;
  pages: { text: string[] }[];
}

export type Language = string  // e.g. 'de', 'en', 'fr'

export function localizeStory(story: Story, lang: Language): { title: string; teaser: string; pages: { text: string[]; image: string }[] } {
  const t = lang !== 'de' ? story.translations?.[lang] : undefined
  return {
    title: t?.title ?? story.title,
    teaser: t?.teaser ?? story.teaser,
    pages: story.pages.map((page, i) => ({
      image: page.image,
      text: t?.pages[i]?.text ?? page.text,
    })),
  }
}
